#!/bin/bash

options=(
  style=round
  width=8.0 # Increased width for a more prominent neon effect
  hidpi=off
  # Active border color: Neon Blue from Tokyo Night Palette
  active_color=0xff7aa2f7
  # Inactive border color: Neon Purple from Tokyo Night Palette
  inactive_color=0xffbb9af7
)

borders "${options[@]}"
